### ISSUE TITLE
Add the ability to query what variables are currently loaded.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [maxdeviant/glenvy#5]
I'm working on a thing that would like to know all the env variables currently loaded with the prefix `THING_`. I'm imagining an api like:

```gleam
glenvy.loaded()
|> list.filter(string.starts_with(_, "THING_")
//=> ["THING_WIBBLE", "THING_WOBBLE"]
```

Does this seem like something glenvy would what to provide?

**Comment by maxdeviant** [comment]
In v1.0.0 you can use [`glenvy/env/get_all`](https://hexdocs.pm/glenvy/1.0.0/glenvy/env.html#get_all) to retrieve all of the environment variables.

In your example it would look like this:

```gleam
import gleam/dict
import gleam/list
import glenvy/env

env.get_all()
|> dict.keys()
|> list.filter(string.starts_with(_, "THING_"))
// => ["THING_WIBBLE", "THING_WOBBLE"]
```

Does that suit your needs?
